# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
 name = "Home"
 pageRef = "/"
 weight = 1

[[main]]
  name = "About Me"
  pageRef = "About Me"
  weight = 2

[[main]]
  name = "Pokemon ROMs"
  pageRef = "Pokemon ROMs"
  weight = 3



[[main]]
  name = "Pokemon Sapphire"
  parent = "Pokemon ROMs"
  pageRef = "Pokemon Sapphire"
  weight = 1

[[main]]
  name = "Pokemon Ruby"
  parent = "Pokemon ROMs"
  pageRef = "Pokemon Ruby"
  weight = 2

[[main]]
  name = "Pokemon Emerald"
  parent = "Pokemon ROMs"
  pageRef = "Pokemon Emerald"
  weight = 3

[[main]]
  name = "Pokemon Red"
  parent = "Pokemon ROMs"
  pageRef = "Pokemon Red"
  weight = 4

[[main]]
  name = "Pokemon Blue"
  parent = "Pokemon ROMs"
  pageRef = "Pokemon Blue"
  weight = 5

[[main]]
  name = "Pokemon Yellow"
  parent = "Pokemon ROMs"
  pageRef = "Pokemon Yellow"
  weight = 6

[[main]]
  name = "Pokemon Gold"
  parent = "Pokemon ROMs"
  pageRef = "Pokemon Gold"
  weight = 7

[[main]]
  name = "Pokemon Silver"
  parent = "Pokemon ROMs"
  pageRef = "Pokemon Silver"
  weight = 8

[[main]]
  name = "Pokemon Crystal"
  parent = "Pokemon ROMs"
  pageRef = "Pokemon Crystal"
  weight = 9


#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 40


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
